[workspace]
resolver = "3"
members = [
    "xtask",
    "cli",
    "engine",
    "engine/lsp",
    "engine/packages/hex/native/lemma_hex",
    "engine/packages/maven/native/lemma_jni",
    "openapi",
]
default-members = ["cli"]
exclude = ["engine/fuzz"]

[workspace.package]
version = "0.9.10"
edition = "2021"
authors = ["Ben Rogmans <ben@lemmabase.com>"]
description = "A pure, declarative language for business rules."
license = "Apache-2.0"
repository = "https://github.com/lemma/lemma"

[workspace.lints.rust]
dead_code = "deny"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.53.1", features = ["full"] }
rust_decimal = { version = "1.42", features = ["serde", "maths"] }
